@rootUrl=http://localhost:49752/v1

### Create Payment
POST {{rootUrl}}/payments
Content-Type: application/json

{
    "orderId": "0c252e6f-8b4c-47ec-be2b-ab5525d80d29",
    "type": "MercadoPago"
}

### Pay Payment
PATCH {{rootUrl}}/payments/07a966c5-82cf-4ab3-817b-a6d83ed4c296
