// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechFood.Infra.Persistence.Contexts;

#nullable disable

namespace TechFood.Infra.Persistence.Migrations
{
    [DbContext(typeof(TechFoodContext))]
    [Migration("20250514225817_SoftDelete")]
    partial class SoftDelete
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TechFood.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageFileName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Category", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("eaa76b46-2e6b-42eb-8f5d-b213f85f25ea"),
                            ImageFileName = "lanche.png",
                            IsDeleted = false,
                            Name = "Lanche",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = new Guid("c65e2cec-bd44-446d-8ed3-a7045cd4876a"),
                            ImageFileName = "acompanhamento.png",
                            IsDeleted = false,
                            Name = "Acompanhamento",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("c3a70938-9e88-437d-a801-c166d2716341"),
                            ImageFileName = "bebida.png",
                            IsDeleted = false,
                            Name = "Bebida",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("ec2fb26d-99a4-4eab-aa5c-7dd18d88a025"),
                            ImageFileName = "sobremesa.png",
                            IsDeleted = false,
                            Name = "Sobremesa",
                            SortOrder = 3
                        });
                });

            modelBuilder.Entity("TechFood.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Customer", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("25b58f54-63bc-42da-8cf6-8162097e72c8"),
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("TechFood.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(6, 2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(6, 2)");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Order", (string)null);
                });

            modelBuilder.Entity("TechFood.Domain.Entities.OrderHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderHistory", (string)null);
                });

            modelBuilder.Entity("TechFood.Domain.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(6, 2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItem", (string)null);
                });

            modelBuilder.Entity("TechFood.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(6, 2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Payment", (string)null);
                });

            modelBuilder.Entity("TechFood.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ImageFileName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("OutOfStock")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(6, 2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Product", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("090d8eb0-f514-4248-8512-cf0d61a262f0"),
                            CategoryId = new Guid("eaa76b46-2e6b-42eb-8f5d-b213f85f25ea"),
                            Description = "Delicioso X-Burguer",
                            ImageFileName = "x-burguer.png",
                            IsDeleted = false,
                            Name = "X-Burguer",
                            OutOfStock = false,
                            Price = 19.99m
                        },
                        new
                        {
                            Id = new Guid("a62dc225-416a-4e36-ba35-a2bd2bbb80f7"),
                            CategoryId = new Guid("eaa76b46-2e6b-42eb-8f5d-b213f85f25ea"),
                            Description = "Delicioso X-Salada",
                            ImageFileName = "x-salada.png",
                            IsDeleted = false,
                            Name = "X-Salada",
                            OutOfStock = false,
                            Price = 21.99m
                        },
                        new
                        {
                            Id = new Guid("3c9374f1-58e9-4b07-bdf6-73aa2f4757ff"),
                            CategoryId = new Guid("eaa76b46-2e6b-42eb-8f5d-b213f85f25ea"),
                            Description = "Delicioso X-Bacon",
                            ImageFileName = "x-bacon.png",
                            IsDeleted = false,
                            Name = "X-Bacon",
                            OutOfStock = false,
                            Price = 22.99m
                        },
                        new
                        {
                            Id = new Guid("55f32e65-c82f-4a10-981c-cdb7b0d2715a"),
                            CategoryId = new Guid("c65e2cec-bd44-446d-8ed3-a7045cd4876a"),
                            Description = "Crocante Batata Frita",
                            ImageFileName = "batata.png",
                            IsDeleted = false,
                            Name = "Batata Frita",
                            OutOfStock = false,
                            Price = 9.99m
                        },
                        new
                        {
                            Id = new Guid("3249b4e4-11e5-41d9-9d55-e9b1d59bfb23"),
                            CategoryId = new Guid("c65e2cec-bd44-446d-8ed3-a7045cd4876a"),
                            Description = "Crocante Batata Frita",
                            ImageFileName = "batata-grande.png",
                            IsDeleted = false,
                            Name = "Batata Frita Grande",
                            OutOfStock = false,
                            Price = 12.99m
                        },
                        new
                        {
                            Id = new Guid("4aeb3ad6-1e06-418e-8878-e66a4ba9337f"),
                            CategoryId = new Guid("c65e2cec-bd44-446d-8ed3-a7045cd4876a"),
                            Description = "Delicioso Nuggets de Frango",
                            ImageFileName = "nuggets.png",
                            IsDeleted = false,
                            Name = "Nuggets de Frango",
                            OutOfStock = false,
                            Price = 13.99m
                        },
                        new
                        {
                            Id = new Guid("86c50c81-c46e-4e79-a591-3b68c75cefda"),
                            CategoryId = new Guid("c3a70938-9e88-437d-a801-c166d2716341"),
                            Description = "Coca-Cola",
                            ImageFileName = "coca-cola.png",
                            IsDeleted = false,
                            Name = "Coca-Cola",
                            OutOfStock = false,
                            Price = 4.99m
                        },
                        new
                        {
                            Id = new Guid("44c61027-8e16-444d-9f4f-e332410cccaa"),
                            CategoryId = new Guid("c3a70938-9e88-437d-a801-c166d2716341"),
                            Description = "Guaraná",
                            ImageFileName = "guarana.png",
                            IsDeleted = false,
                            Name = "Guaraná",
                            OutOfStock = false,
                            Price = 4.99m
                        },
                        new
                        {
                            Id = new Guid("bf90f247-52cc-4bbb-b6e3-9c77b6ff546f"),
                            CategoryId = new Guid("c3a70938-9e88-437d-a801-c166d2716341"),
                            Description = "Fanta",
                            ImageFileName = "fanta.png",
                            IsDeleted = false,
                            Name = "Fanta",
                            OutOfStock = false,
                            Price = 4.99m
                        },
                        new
                        {
                            Id = new Guid("8620cf54-0d37-4aa1-832a-eb98e9b36863"),
                            CategoryId = new Guid("c3a70938-9e88-437d-a801-c166d2716341"),
                            Description = "Sprite",
                            ImageFileName = "sprite.png",
                            IsDeleted = false,
                            Name = "Sprite",
                            OutOfStock = false,
                            Price = 4.99m
                        },
                        new
                        {
                            Id = new Guid("de797d9f-c473-4bed-a560-e7036ca10ab1"),
                            CategoryId = new Guid("ec2fb26d-99a4-4eab-aa5c-7dd18d88a025"),
                            Description = "Milk Shake de Morango",
                            ImageFileName = "milk-shake-morango.png",
                            IsDeleted = false,
                            Name = "Milk Shake de Morango",
                            OutOfStock = false,
                            Price = 7.99m
                        },
                        new
                        {
                            Id = new Guid("113daae6-f21f-4d38-a778-9364ac64f909"),
                            CategoryId = new Guid("ec2fb26d-99a4-4eab-aa5c-7dd18d88a025"),
                            Description = "Milk Shake de Chocolate",
                            ImageFileName = "milk-shake-chocolate.png",
                            IsDeleted = false,
                            Name = "Milk Shake de Chocolate",
                            OutOfStock = false,
                            Price = 7.99m
                        },
                        new
                        {
                            Id = new Guid("2665c2ec-c537-4d95-9a0f-791bcd4cc938"),
                            CategoryId = new Guid("ec2fb26d-99a4-4eab-aa5c-7dd18d88a025"),
                            Description = "Milk Shake de Baunilha",
                            ImageFileName = "milk-shake-baunilha.png",
                            IsDeleted = false,
                            Name = "Milk Shake de Baunilha",
                            OutOfStock = false,
                            Price = 7.99m
                        });
                });

            modelBuilder.Entity("TechFood.Domain.Entities.Customer", b =>
                {
                    b.OwnsOne("TechFood.Domain.ValueObjects.Document", "Document", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Type")
                                .HasColumnType("int")
                                .HasColumnName("DocumentType");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("varchar(20)")
                                .HasColumnName("DocumentValue");

                            b1.HasKey("CustomerId");

                            b1.ToTable("Customer");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");

                            b1.HasData(
                                new
                                {
                                    CustomerId = new Guid("25b58f54-63bc-42da-8cf6-8162097e72c8"),
                                    Type = 0,
                                    Value = "4511554544"
                                });
                        });

                    b.OwnsOne("TechFood.Domain.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("varchar(255)")
                                .HasColumnName("EmailAddress");

                            b1.HasKey("CustomerId");

                            b1.ToTable("Customer");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");

                            b1.HasData(
                                new
                                {
                                    CustomerId = new Guid("25b58f54-63bc-42da-8cf6-8162097e72c8"),
                                    Address = "john.dev@gmail.com"
                                });
                        });

                    b.OwnsOne("TechFood.Domain.ValueObjects.Name", "Name", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("FullName")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("varchar(255)")
                                .HasColumnName("NameFullName");

                            b1.HasKey("CustomerId");

                            b1.ToTable("Customer");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");

                            b1.HasData(
                                new
                                {
                                    CustomerId = new Guid("25b58f54-63bc-42da-8cf6-8162097e72c8"),
                                    FullName = "John"
                                });
                        });

                    b.OwnsOne("TechFood.Domain.ValueObjects.Phone", "Phone", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("CountryCode")
                                .IsRequired()
                                .HasMaxLength(5)
                                .HasColumnType("varchar(5)")
                                .HasColumnName("PhoneCountryCode");

                            b1.Property<string>("DDD")
                                .IsRequired()
                                .HasMaxLength(4)
                                .HasColumnType("varchar(4)")
                                .HasColumnName("PhoneDDD");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(15)
                                .HasColumnType("varchar(15)")
                                .HasColumnName("PhoneNumber");

                            b1.HasKey("CustomerId");

                            b1.ToTable("Customer");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");

                            b1.HasData(
                                new
                                {
                                    CustomerId = new Guid("25b58f54-63bc-42da-8cf6-8162097e72c8"),
                                    CountryCode = "55",
                                    DDD = "11",
                                    Number = "9415452222"
                                });
                        });

                    b.Navigation("Document")
                        .IsRequired();

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Phone");
                });

            modelBuilder.Entity("TechFood.Domain.Entities.Order", b =>
                {
                    b.HasOne("TechFood.Domain.Entities.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId");
                });

            modelBuilder.Entity("TechFood.Domain.Entities.OrderHistory", b =>
                {
                    b.HasOne("TechFood.Domain.Entities.Order", null)
                        .WithMany("Historical")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TechFood.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("TechFood.Domain.Entities.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechFood.Domain.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TechFood.Domain.Entities.Product", b =>
                {
                    b.HasOne("TechFood.Domain.Entities.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TechFood.Domain.Entities.Order", b =>
                {
                    b.Navigation("Historical");

                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
