// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechFood.Infra.Persistence.Contexts;

#nullable disable

namespace TechFood.Infra.Persistence.Migrations
{
    [DbContext(typeof(TechFoodContext))]
    [Migration("20250509005936_PaymentAsRoot")]
    partial class PaymentAsRoot
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TechFood.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageFileName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Category", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("eaa76b46-2e6b-42eb-8f5d-b213f85f25ea"),
                            ImageFileName = "lanche.png",
                            Name = "Lanche"
                        },
                        new
                        {
                            Id = new Guid("c65e2cec-bd44-446d-8ed3-a7045cd4876a"),
                            ImageFileName = "acompanhamento.png",
                            Name = "Acompanhamento"
                        },
                        new
                        {
                            Id = new Guid("c3a70938-9e88-437d-a801-c166d2716341"),
                            ImageFileName = "bebida.png",
                            Name = "Bebida"
                        },
                        new
                        {
                            Id = new Guid("ec2fb26d-99a4-4eab-aa5c-7dd18d88a025"),
                            ImageFileName = "sobremesa.png",
                            Name = "Sobremesa"
                        });
                });

            modelBuilder.Entity("TechFood.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Customer", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("25b58f54-63bc-42da-8cf6-8162097e72c8")
                        });
                });

            modelBuilder.Entity("TechFood.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(6, 2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(6, 2)");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Order", (string)null);
                });

            modelBuilder.Entity("TechFood.Domain.Entities.OrderHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderHistory", (string)null);
                });

            modelBuilder.Entity("TechFood.Domain.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(6, 2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItem", (string)null);
                });

            modelBuilder.Entity("TechFood.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(6, 2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Payment", (string)null);
                });

            modelBuilder.Entity("TechFood.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ImageFileName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("OutOfStock")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(6, 2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Product", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("090d8eb0-f514-4248-8512-cf0d61a262f0"),
                            CategoryId = new Guid("eaa76b46-2e6b-42eb-8f5d-b213f85f25ea"),
                            Description = "Delicioso X-Burguer",
                            ImageFileName = "lanche-carnes.png",
                            Name = "X-Burguer",
                            OutOfStock = false,
                            Price = 19.99m
                        },
                        new
                        {
                            Id = new Guid("55f32e65-c82f-4a10-981c-cdb7b0d2715a"),
                            CategoryId = new Guid("c65e2cec-bd44-446d-8ed3-a7045cd4876a"),
                            Description = "Crocante Batata Frita",
                            ImageFileName = "bebida-gelada.png",
                            Name = "Batata Frita",
                            OutOfStock = false,
                            Price = 9.99m
                        },
                        new
                        {
                            Id = new Guid("86c50c81-c46e-4e79-a591-3b68c75cefda"),
                            CategoryId = new Guid("c3a70938-9e88-437d-a801-c166d2716341"),
                            Description = "Gelado Refrigerante",
                            ImageFileName = "bebida-gelada.png",
                            Name = "Refrigerante",
                            OutOfStock = false,
                            Price = 4.99m
                        },
                        new
                        {
                            Id = new Guid("de797d9f-c473-4bed-a560-e7036ca10ab1"),
                            CategoryId = new Guid("ec2fb26d-99a4-4eab-aa5c-7dd18d88a025"),
                            Description = "Doce Pudim",
                            ImageFileName = "bebida-gelada.png",
                            Name = "Pudim",
                            OutOfStock = false,
                            Price = 7.99m
                        });
                });

            modelBuilder.Entity("TechFood.Domain.Entities.Customer", b =>
                {
                    b.OwnsOne("TechFood.Domain.ValueObjects.Document", "Document", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Type")
                                .HasColumnType("int")
                                .HasColumnName("DocumentType");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("varchar(20)")
                                .HasColumnName("DocumentValue");

                            b1.HasKey("CustomerId");

                            b1.ToTable("Customer");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");

                            b1.HasData(
                                new
                                {
                                    CustomerId = new Guid("25b58f54-63bc-42da-8cf6-8162097e72c8"),
                                    Type = 0,
                                    Value = "4511554544"
                                });
                        });

                    b.OwnsOne("TechFood.Domain.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("varchar(255)")
                                .HasColumnName("EmailAddress");

                            b1.HasKey("CustomerId");

                            b1.ToTable("Customer");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");

                            b1.HasData(
                                new
                                {
                                    CustomerId = new Guid("25b58f54-63bc-42da-8cf6-8162097e72c8"),
                                    Address = "john.dev@gmail.com"
                                });
                        });

                    b.OwnsOne("TechFood.Domain.ValueObjects.Name", "Name", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("FullName")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("varchar(255)")
                                .HasColumnName("NameFullName");

                            b1.HasKey("CustomerId");

                            b1.ToTable("Customer");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");

                            b1.HasData(
                                new
                                {
                                    CustomerId = new Guid("25b58f54-63bc-42da-8cf6-8162097e72c8"),
                                    FullName = "John"
                                });
                        });

                    b.OwnsOne("TechFood.Domain.ValueObjects.Phone", "Phone", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("CountryCode")
                                .IsRequired()
                                .HasMaxLength(5)
                                .HasColumnType("varchar(5)")
                                .HasColumnName("PhoneCountryCode");

                            b1.Property<string>("DDD")
                                .IsRequired()
                                .HasMaxLength(4)
                                .HasColumnType("varchar(4)")
                                .HasColumnName("PhoneDDD");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(15)
                                .HasColumnType("varchar(15)")
                                .HasColumnName("PhoneNumber");

                            b1.HasKey("CustomerId");

                            b1.ToTable("Customer");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");

                            b1.HasData(
                                new
                                {
                                    CustomerId = new Guid("25b58f54-63bc-42da-8cf6-8162097e72c8"),
                                    CountryCode = "55",
                                    DDD = "11",
                                    Number = "9415452222"
                                });
                        });

                    b.Navigation("Document")
                        .IsRequired();

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Phone");
                });

            modelBuilder.Entity("TechFood.Domain.Entities.Order", b =>
                {
                    b.HasOne("TechFood.Domain.Entities.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId");
                });

            modelBuilder.Entity("TechFood.Domain.Entities.OrderHistory", b =>
                {
                    b.HasOne("TechFood.Domain.Entities.Order", null)
                        .WithMany("Historical")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TechFood.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("TechFood.Domain.Entities.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechFood.Domain.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TechFood.Domain.Entities.Product", b =>
                {
                    b.HasOne("TechFood.Domain.Entities.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TechFood.Domain.Entities.Order", b =>
                {
                    b.Navigation("Historical");

                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
