ARG DOTNET_RUNTIME=mcr.microsoft.com/dotnet/aspnet:8.0
ARG DOTNET_SDK=mcr.microsoft.com/dotnet/sdk:8.0

FROM ${DOTNET_RUNTIME} AS base
RUN apt-get update && \
    apt-get install wget -y
WORKDIR /app
EXPOSE 8080

FROM ${DOTNET_SDK} AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["src/TechFood.Order.Worker/TechFood.Order.Worker.csproj", "TechFood.Order.Worker/"]
COPY ["src/TechFood.Order.Application/TechFood.Order.Application.csproj", "TechFood.Order.Application/"]
COPY ["src/TechFood.Order.Contracts/TechFood.Order.Contracts.csproj", "TechFood.Order.Contracts/"]
COPY ["src/TechFood.Order.Domain/TechFood.Order.Domain.csproj", "TechFood.Order.Domain/"]
COPY ["src/TechFood.Order.Infra/TechFood.Order.Infra.csproj", "TechFood.Order.Infra/"]
RUN dotnet restore "./TechFood.Order.Worker/TechFood.Order.Worker.csproj"
COPY /src .
WORKDIR TechFood.Order.Worker
RUN dotnet build "./TechFood.Order.Worker.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./TechFood.Order.Worker.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "TechFood.Order.Worker.dll"]
