// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechFood.Order.Infra.Persistence.Contexts;

#nullable disable

namespace TechFood.Order.Infra.Migrations
{
    [DbContext(typeof(OrderContext))]
    partial class OrderContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TechFood.Order.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(6, 2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(6, 2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Order", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d1b5f3a2-4c8e-4b7c-9f0e-5a2d6f3b8c1e"),
                            Amount = 39.97m,
                            CreatedAt = new DateTime(2025, 5, 13, 22, 2, 36, 0, DateTimeKind.Utc).AddTicks(6053),
                            CustomerId = new Guid("25b58f54-63bc-42da-8cf6-8162097e72c8"),
                            Discount = 0m,
                            IsDeleted = false,
                            Number = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("f2b5f3a2-4c8e-4b7c-9f0e-5a2d6f3b8c1e"),
                            Amount = 26.98m,
                            CreatedAt = new DateTime(2025, 5, 13, 22, 2, 36, 0, DateTimeKind.Utc).AddTicks(6354),
                            CustomerId = new Guid("9887b301-605f-46a6-93db-ac1ce8685723"),
                            Discount = 0m,
                            IsDeleted = false,
                            Number = 2,
                            Status = 3
                        });
                });

            modelBuilder.Entity("TechFood.Order.Domain.Entities.OrderHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderHistory", (string)null);
                });

            modelBuilder.Entity("TechFood.Order.Domain.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(6, 2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItem");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ea31fb90-4bc3-418f-95fc-56516d5bc634"),
                            IsDeleted = false,
                            OrderId = new Guid("d1b5f3a2-4c8e-4b7c-9f0e-5a2d6f3b8c1e"),
                            ProductId = new Guid("090d8eb0-f514-4248-8512-cf0d61a262f0"),
                            Quantity = 1,
                            UnitPrice = 19.99m
                        },
                        new
                        {
                            Id = new Guid("b0f1c3a2-4c8e-4b7c-9f0e-5a2d6f3b8c1e"),
                            IsDeleted = false,
                            OrderId = new Guid("d1b5f3a2-4c8e-4b7c-9f0e-5a2d6f3b8c1e"),
                            ProductId = new Guid("55f32e65-c82f-4a10-981c-cdb7b0d2715a"),
                            Quantity = 2,
                            UnitPrice = 9.99m
                        },
                        new
                        {
                            Id = new Guid("82e5700b-c33e-40a6-bb68-7279f0509421"),
                            IsDeleted = false,
                            OrderId = new Guid("f2b5f3a2-4c8e-4b7c-9f0e-5a2d6f3b8c1e"),
                            ProductId = new Guid("a62dc225-416a-4e36-ba35-a2bd2bbb80f7"),
                            Quantity = 1,
                            UnitPrice = 21.99m
                        },
                        new
                        {
                            Id = new Guid("900f65fe-47ca-4b4b-9a7c-a82c6d9c52cd"),
                            IsDeleted = false,
                            OrderId = new Guid("f2b5f3a2-4c8e-4b7c-9f0e-5a2d6f3b8c1e"),
                            ProductId = new Guid("86c50c81-c46e-4e79-a591-3b68c75cefda"),
                            Quantity = 1,
                            UnitPrice = 4.99m
                        });
                });

            modelBuilder.Entity("TechFood.Order.Domain.Entities.OrderHistory", b =>
                {
                    b.HasOne("TechFood.Order.Domain.Entities.Order", null)
                        .WithMany("Historical")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TechFood.Order.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("TechFood.Order.Domain.Entities.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TechFood.Order.Domain.Entities.Order", b =>
                {
                    b.Navigation("Historical");

                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
